In [2]:
#import the necessary packages

import pandas as pd

In [3]:
#read from the csv file
df_2016=pd.read_csv("/Users/chidam/Desktop/500_Cities__City-level_Data__GIS_Friendly_Format___2016_release.csv")

In [4]:
#check the top 5 records to get an idea

df_2016.head()

,StateAbbr,PlaceName,PlaceFIPS,Population2010,ACCESS2_CrudePrev,ACCESS2_Crude95CI,ACCESS2_AdjPrev,ACCESS2_Adj95CI,ARTHRITIS_CrudePrev,ARTHRITIS_Crude95CI,...,SLEEP_Adj95CI,STROKE_CrudePrev,STROKE_Crude95CI,STROKE_AdjPrev,STROKE_Adj95CI,TEETHLOST_CrudePrev,TEETHLOST_Crude95CI,TEETHLOST_AdjPrev,TEETHLOST_Adj95CI,Geolocation
0,FL,Deltona,1217200,"85,182",24.3,"(23.7, 25.0)",23.7,"(23.0, 24.3)",26.0,"(25.8, 26.3)",...,"(36.8, 37.5)",3.2,"( 3.2, 3.3)",3.0,"( 3.0, 3.1)",14.8,"(13.8, 15.8)",14.8,"(13.8, 15.8)","(28.905060048, -81.2134269839)"
1,FL,Fort Lauderdale,1224000,"165,521",22.5,"(22.0, 23.0)",22.0,"(21.5, 22.6)",25.8,"(25.7, 26.1)",...,"(38.1, 38.6)",3.6,"( 3.5, 3.6)",3.2,"( 3.2, 3.3)",12.1,"(11.3, 12.8)",12.1,"(11.3, 12.8)","(26.1418205174, -80.1471225502)"
2,NC,Fayetteville,3722920,"200,564",21.0,"(20.6, 21.4)",19.2,"(18.8, 19.5)",24.4,"(24.3, 24.6)",...,"(39.7, 40.1)",3.1,"( 3.1, 3.2)",3.6,"( 3.5, 3.7)",18.3,"(17.5, 19.3)",18.4,"(17.4, 19.4)","(35.0851309527, -78.9791676456)"
3,NC,Gastonia,3725580,"71,741",25.3,"(24.7, 25.8)",24.6,"(24.1, 25.2)",30.0,"(29.7, 30.3)",...,"(38.4, 39.0)",4.0,"( 3.9, 4.1)",3.7,"( 3.7, 3.8)",22.4,"(21.0, 24.0)",22.2,"(20.9, 23.9)","(35.2472984431, -81.1836588468)"
4,CA,Lake Forest,639496,"77,264",11.4,"(10.9, 11.9)",11.0,"(10.6, 11.6)",17.5,"(17.2, 17.8)",...,"(29.9, 30.6)",2.0,"( 2.0, 2.1)",2.2,"( 2.1, 2.3)",8.2,"( 6.9, 9.8)",8.3,"( 7.1, 9.9)","(33.6634128948, -117.670683341)"

In [5]:
#chekc the length of the dataframe
len(df_2016)

500

In [17]:
#number of unique values in the column: StateAbbr. It should be 50 (for 50 states) but we have 51. 

len(df_2016["StateAbbr"].value_counts())

51

In [18]:
#checking the values in the column: StateAbbr

df_2016["StateAbbr"].value_counts()

CA    121
TX     47
FL     33
IL     18
MI     16
CO     14
NC     14
WA     14
MA     13
AZ     12
VA     11
GA     11
IN     11
UT      9
NY      9
OH      9
NJ      9
CT      8
MO      8
OR      8
WI      7
MN      7
PA      7
LA      6
IA      6
TN      6
OK      6
KS      6
AL      6
SC      5
NV      5
AR      5
RI      4
NM      4
ID      3
NH      2
KY      2
MT      2
MS      2
SD      2
NE      2
HI      1
ME      1
ND      1
DC      1
MD      1
AK      1
WV      1
DE      1
WY      1
VT      1
Name: StateAbbr, dtype: int64

In [20]:
# Looks like we have data points for 474 US cities

len(df_2016["PlaceName"].value_counts())

474

In [21]:
#let's check how many of the values PlaceName match with that of the cities in the 


df_harvard_gh=pd.read_csv("/Users/chidam/Desktop/hospital-capacity-by-state-60-population-contracted.csv")

In [22]:
df_harvard_gh.head()

,state,total_hospital_beds,total_icu_beds,hospital_bed_occupancy_rate,icu_bed_occupancy_rate,available_hospital_beds,potentially_available_hospital_beds,available_icu_beds,potentially_available_icu_beds,adult_population,...,percentage_of_potentially_available_icu_beds_needed_six_months,percentage_of_total_icu_beds_needed_six_months,icu_beds_needed_twelve_months,percentage_of_available_icu_beds_needed_twelve_months,percentage_of_potentially_available_icu_beds_needed_twelve_months,percentage_of_total_icu_beds_needed_twelve_months,icu_beds_needed_eighteen_months,percentage_of_available_icu_beds_needed_eighteen_months,percentage_of_potentially_available_icu_beds_needed_eighteen_months,percentage_of_total_icu_beds_needed_eighteen_months
0,AK,1583.0,130.0,0.66,0.58,533.0,1058.0,55.0,93.0,552319.0,...,10.02,7.17,466.0,8.47,5.01,3.58,304.0,5.53,3.27,2.34
1,AL,13959.0,1870.0,0.64,0.68,4994.0,9476.0,606.0,1238.0,3748089.0,...,5.48,3.63,3394.0,5.60,2.74,1.81,2213.0,3.65,1.79,1.18
2,AR,8428.0,856.0,0.52,0.58,4069.0,6248.0,362.0,609.0,2272226.0,...,6.80,4.84,2070.0,5.72,3.40,2.42,1350.0,3.73,2.22,1.58
3,AZ,12868.0,1742.0,0.62,0.53,4938.0,8903.0,814.0,1278.0,5187520.0,...,7.42,5.45,4744.0,5.83,3.71,2.72,3094.0,3.80,2.42,1.78
4,CA,68554.0,8131.0,0.67,0.58,22831.0,45692.0,3381.0,5756.0,29868127.0,...,9.11,6.45,26211.0,7.75,4.55,3.22,17094.0,5.06,2.97,2.10

In [23]:
#in the harvard_global_health dataset we have values only for the states
len(df_harvard_gh)

54

In [35]:
#number of unique states in df_harvard_gh
len(df_harvard_gh["state"].unique())

54

In [24]:
#what about the 


df_definitive_hc_hospitalbeds=pd.read_csv("/Users/chidam/Desktop/definitive-healthcare-usa-hospital-beds.csv")

In [25]:
df_definitive_hc_hospitalbeds.head()

,geometry,objectid,hospital_n,hospital_t,hq_address,hq_addre_1,hq_city,hq_state,hq_zip_cod,county_nam,state_name,state_fips,cnty_fips,fips,num_licens,num_staffe,num_icu_be,bed_utiliz,potential
0,POINT (-112.0661569 33.4954978),1,Phoenix VA Health Care System (AKA Carl T Hayd...,VA Hospital,650 E Indian School Rd,NaN,Phoenix,AZ,85012,Maricopa,Arizona,4.0,13.0,4013.0,62,62,NaN,NaN,0
1,POINT (-110.9658852 32.1812634),2,Southern Arizona VA Health Care System,VA Hospital,3601 S 6th Ave,NaN,Tucson,AZ,85723,Pima,Arizona,4.0,19.0,4019.0,****,****,NaN,NaN,0
2,POINT (-119.7797421 36.7733235),3,VA Central California Health Care System,VA Hospital,2615 E Clinton Ave,NaN,Fresno,CA,93703,Fresno,California,6.0,19.0,6019.0,****,****,NaN,NaN,0
3,POINT (-72.9576103 41.2844004),4,VA Connecticut Healthcare System - West Haven ...,VA Hospital,950 Campbell Ave,NaN,West Haven,CT,6516,New Haven,Connecticut,9.0,9.0,9009.0,216,216,NaN,NaN,0
4,POINT (-75.6065325 39.7402063),5,Wilmington VA Medical Center,VA Hospital,1601 Kirkwood Hwy,NaN,Wilmington,DE,19805,New Castle,Delaware,10.0,3.0,10003.0,****,****,NaN,NaN,0

In [26]:
len(df_definitive_hc_hospitalbeds)

6581

In [27]:
#this dataset has data points for a lot more cities than df_2016

len(df_definitive_hc_hospitalbeds["hq_city"].value_counts())

3175

In [28]:
#checking the unique number of states in the column

len(df_definitive_hc_hospitalbeds["hq_state"].value_counts())

56

In [33]:
df_definitive_hc_hospitalbeds["hq_state"].unique()

# Note: #there are 51 number of unique values in the column: StateAbbr in the dataset: df_2016
# also 56 in df_definitive_hc_hospitalbeds["hq_state"] and 54 in df_harvard_gh

array(['AZ', 'CA', 'CT', 'DE', 'DC', 'FL', 'ID', 'LA', 'MS', 'MO', 'NM',
       'NY', 'ND', 'OR', 'PA', 'AL', 'AK', 'ME', 'MD', 'MA', 'AR', 'RI',
       'SC', 'WV', 'CO', 'GA', 'HI', 'MN', 'MT', 'NE', 'NV', 'NH', 'NJ',
       'NC', 'OH', 'TX', 'UT', 'IL', 'OK', 'PR', 'MI', 'IA', 'IN', 'KS',
       'KY', 'VA', 'GU', 'WI', 'TN', 'VT', 'WA', 'WY', 'SD', 'AS', 'MP',
       'VI'], dtype=object)

In [37]:
#next let's check how mnay of the 474 cities in df_2016 match with that of df_definitive_hc_hospitalbeds



df_definitive_hc_hospitalbeds["hq_city"].unique().tolist()

['Phoenix',
 'Tucson',
 'Fresno',
 'West Haven',
 'Wilmington',
 'Washington',
 'Gainesville',
 'Boise',
 'Shreveport',
 'Flowood',
 'Columbia',
 'Albuquerque',
 'Albany',
 'Bronx',
 'Fargo',
 'Roseburg',
 'Pittsburgh',
 'Prattville',
 'Fairhope',
 'Bay Minette',
 'Eufaula',
 'Centreville',
 'Oneonta',
 'Union Springs',
 'Greenville',
 'Anniston',
 'Valley',
 'Centre',
 'Grove Hill',
 'Jackson',
 'Ashland',
 'Enterprise',
 'Muscle Shoals',
 'Evergreen',
 'Andalusia',
 'Opp',
 'Luverne',
 'Cullman',
 'Ozark',
 'Selma',
 'Fort Payne',
 'Tallassee',
 'Wetumpka',
 'Brewton',
 'Atmore',
 'Gadsden',
 'Fayette',
 'Russellville',
 'Red Bay',
 'Geneva',
 'Eutaw',
 'Greensboro',
 'Dothan',
 'Scottsboro',
 'Birmingham',
 'Sheffield',
 'Bessemer',
 'Florence',
 'Moulton',
 'Opelika',
 'Athens',
 'Huntsville',
 'Demopolis',
 'Winfield',
 'Hamilton',
 'Boaz',
 'Mobile',
 'Monroeville',
 'Montgomery',
 'Decatur',
 'Troy',
 'Phenix City',
 'Pell City',
 'Alabaster',
 'York',
 'Sylacauga',
 'Talladega',
 'Dadeville',
 'Alexander City',
 'Tuscaloosa',
 'Jasper',
 'Chatom',
 'Camden',
 'Haleyville',
 'Anchorage',
 'Bethel',
 'Augusta',
 'Fairbanks',
 'Juneau',
 'Soldotna',
 'Seward',
 'Homer',
 'Ketchikan',
 'Baltimore',
 'Kodiak',
 'Palmer',
 'Nome',
 'Sitka',
 'Wrangell',
 'Leeds',
 'Bedford',
 'Fort Defiance',
 'Chinle',
 'Ganado',
 'Springerville',
 'Bisbee',
 'Benson',
 'Willcox',
 'Sierra Vista',
 'Flagstaff',
 'Page',
 'Tuba City',
 'Peridot',
 'Globe',
 'Payson',
 'Safford',
 'Parker',
 'Mesa',
 'Sun City',
 'Chandler',
 'Scottsdale',
 'Glendale',
 'Sun City West',
 'Goodyear',
 'Wickenburg',
 'Gilbert',
 'Fort Mohave',
 'Bullhead City',
 'Lake Havasu City',
 'Kingman',
 'Show Low',
 'Polacca',
 'Whiteriver',
 'Winslow',
 'Oro Valley',
 'Sells',
 'Casa Grande',
 'Nogales',
 'Prescott',
 'Cottonwood',
 'Yuma',
 'Stuttgart',
 'De Witt',
 'Crossett',
 'Mountain Home',
 'Siloam Springs',
 'Rogers',
 'Gravette',
 'Harrison',
 'Warren',
 'Berryville',
 'Lake Village',
 'Arkadelphia',
 'Piggott',
 'Heber Springs',
 'Magnolia',
 'Providence',
 'Morrilton',
 'Jonesboro',
 'Van Buren',
 'Wynne',
 'Fordyce',
 'McGehee',
 'Dumas',
 'Monticello',
 'Conway',
 'Hot Springs',
 'Paragould',
 'Hope',
 'Malvern',
 'Charleston',
 'Nashville',
 'Batesville',
 'Pine Bluff',
 'Clarksville',
 'Walnut Ridge',
 'Paris',
 'Booneville',
 'Osceola',
 'Blytheville',
 'Helena',
 'Mena',
 'North Little Rock',
 'Little Rock',
 'Sherwood',
 'Pocahontas',
 'Forrest City',
 'Benton',
 'Waldron',
 'Fort Smith',
 'Mountain View',
 'El Dorado',
 'Clinton',
 'Fayetteville',
 'Springdale',
 'Searcy',
 'Danville',
 'Dardanelle',
 'Hayward',
 'Oakland',
 'San Leandro',
 'Fremont',
 'Alameda',
 'Pleasanton',
 'Berkeley',
 'Castro Valley',
 'Chico',
 'Oroville',
 'San Andreas',
 'Concord',
 'Antioch',
 'San Ramon',
 'Martinez',
 'Walnut Creek',
 'Crescent City',
 'Placerville',
 'South Lake Tahoe',
 'Reedley',
 'Clovis',
 'Willows',
 'Garberville',
 'Fortuna',
 'Arcata',
 'Eureka',
 'Martinsburg',
 'El Centro',
 'Brawley',
 'Lone Pine',
 'Bishop',
 'Lake Isabella',
 'Tehachapi',
 'Bakersfield',
 'Delano',
 'Ridgecrest',
 'Hanford',
 'Clearlake',
 'Lakeport',
 'Susanville',
 'Avalon',
 'Los Angeles',
 'Long Beach',
 'Van Nuys',
 'San Gabriel',
 'Panorama City',
 'Downey',
 'Whittier',
 'Duarte',
 'Encino',
 'Huntington Park',
 'West Covina',
 'Lynwood',
 'Santa Monica',
 'Northridge',
 'San Pedro',
 'Norwalk',
 'Palmdale',
 'Glendora',
 'Pomona',
 'Burbank',
 'Arcadia',
 'Mission Hills',
 'Alhambra',
 'Torrance',
 'Montebello',
 'Sun Valley',
 'Covina',
 'Pasadena',
 'Harbor City',
 'Gardena',
 'West Hills',
 'Bellflower',
 'Baldwin Park',
 'Monterey Park',
 'South El Monte',
 'Inglewood',
 'Marina Del Rey',
 'Tarzana',
 'Sherman Oaks',
 'Valencia',
 'Lakewood',
 'San Dimas',
 'Woodland Hills',
 'Sylmar',
 'Lancaster',
 'Madera',
 'San Rafael',
 'Greenbrae',
 'Novato',
 'Mariposa',
 'Willits',
 'Fort Bragg',
 'Ukiah',
 'Merced',
 'Los Banos',
 'Cedarville',
 'Salinas',
 'Monterey',
 'King City',
 'Napa',
 'Saint Helena',
 'Grass Valley',
 'Truckee',
 'Fullerton',
 'Orange',
 'Anaheim',
 'Newport Beach',
 'Garden Grove',
 'Huntington Beach',
 'Fountain Valley',
 'Mission Viejo',
 'Costa Mesa',
 'Los Alamitos',
 'Placentia',
 'La Palma',
 'Laguna Hills',
 'Santa Ana',
 'Auburn',
 'Roseville',
 'Portola',
 'Quincy',
 'Chester',
 'Moreno Valley',
 'Menifee',
 'Riverside',
 'Rancho Mirage',
 'Indio',
 'Blythe',
 'Hemet',
 'Corona',
 'Palm Springs',
 'Banning',
 'Sacramento',
 'Mather',
 'Folsom',
 'Carmichael',
 'Hollister',
 'Barstow',
 'Apple Valley',
 'Loma Linda',
 'Colton',
 'Joshua Tree',
 'Redlands',
 'Upland',
 'San Bernardino',
 'Fontana',
 'Chino',
 'Big Bear Lake',
 'Montclair',
 'Victorville',
 'Needles',
 'Lake Arrowhead',
 'San Diego',
 'Encinitas',
 'La Jolla',
 'Poway',
 'Escondido',
 'Oceanside',
 'Coronado',
 'Chula Vista',
 'National City',
 'La Mesa',
 'San Francisco',
 'Lodi',
 'Manteca',
 'French Camp',
 'Stockton',
 'Tracy',
 'San Luis Obispo',
 'Templeton',
 'Arroyo Grande',
 'Burlingame',
 'Redwood City',
 'Menlo Park',
 'Daly City',
 'San Mateo',
 'South San Francisco',
 'Lompoc',
 'Santa Maria',
 'Goleta',
 'Santa Barbara',
 'Solvang',
 'Palo Alto',
 'San Jose',
 'Gilroy',
 'Santa Clara',
 'Watsonville',
 'Santa Cruz',
 'Redding',
 'Fall River Mills',
 'Mount Shasta',
 'Yreka',
 'Vallejo',
 'Fairfield',
 'Sebastopol',
 'Santa Rosa',
 'Sonoma',
 'Petaluma',
 'Healdsburg',
 'Turlock',
 'Oakdale',
 'Modesto',
 'Yuba City',
 'Red Bluff',
 'Weaverville',
 'Visalia',
 'Tulare',
 'Porterville',
 'Sonora',
 'Simi Valley',
 'Oxnard',
 'Ventura',
 'Camarillo',
 'Thousand Oaks',
 'Ojai',
 'Davis',
 'Woodland',
 'Marysville',
 'Brighton',
 'Aurora',
 'Thornton',
 'Alamosa',
 'Englewood',
 'Lone Tree',
 'Littleton',
 'Pagosa Springs',
 'Lafayette',
 'Louisville',
 'Longmont',
 'Salida',
 'Cheyenne Wells',
 'Delta',
 'Denver',
 'Vail',
 'Colorado Springs',
 'Canon City',
 'Glenwood Springs',
 'Rifle',
 'Gunnison',
 'Walsenburg',
 'Westminster',
 'Wheat Ridge',
 'Burlington',
 'Leadville',
 'Durango',
 'Loveland',
 'Fort Collins',
 'Estes Park',
 'Trinidad',
 'Sterling',
 'Grand Junction',
 'Craig',
 'Cortez',
 'Montrose',
 'Fort Morgan',
 'Brush',
 'La Junta',
 'Holyoke',
 'Aspen',
 'Lamar',
 'Pueblo',
 'Meeker',
 'Rangely',
 'Del Norte',
 'Steamboat Springs',
 'Frisco',
 'Woodland Park',
 'Greeley',
 'Wray',
 'Stamford',
 'Bridgeport',
 'Greenwich',
 'Danbury',
 'Southington',
 'Farmington',
 'Hartford',
 'Manchester',
 'Bristol',
 'West Hartford',
 'Sharon',
 'Torrington',
 'Middletown',
 'Milford',
 'Waterbury',
 'Meriden',
 'New Haven',
 'Branford',
 'Wallingford',
 'Derby',
 'New London',
 'Norwich',
 'Vernon',
 'Stafford Springs',
 'Putnam',
 'Willimantic',
 'Dover',
 'Newark',
 'Seaford',
 'Lewes',
 'Panama City',
 'Starke',
 'Melbourne',
 'Titusville',
 'Rockledge',
 'Cocoa Beach',
 'Plantation',
 'Pembroke Pines',
 'Margate',
 'Fort Lauderdale',
 'Tamarac',
 'Deerfield Beach',
 'Hollywood',
 'Weston',
 'Miramar',
 'Coral Springs',
 'Punta Gorda',
 'Port Charlotte',
 'Crystal River',
 'Inverness',
 'Orange Park',
 'Naples',
 'Lake City',
 'Jacksonville',
 'Jacksonville Beach',
 'Pensacola',
 'Palm Coast',
 'Chattahoochee',
 'Wauchula',
 'Clewiston',
 'Brooksville',
 'Sebring',
 'Tampa',
 'Plant City',
 'Brandon',
 'Sun City Center',
 'Bonifay',
 'Vero Beach',
 'Sebastian',
 'Marianna',
 'The Villages',
 'Leesburg',
 'Tavares',
 'Clermont',
 'Lehigh Acres',
 'Fort Myers',
 'Cape Coral',
 'Tallahassee',
 'Bradenton',
 'Ocala',
 'Stuart',
 'Miami Beach',
 'Hialeah',
 'Miami',
 'South Miami',
 'Coral Gables',
 'Homestead',
 'Aventura',
 'Key West',
 'Tavernier',
 'Marathon',
 'Fernandina Beach',
 'Crestview',
 'Fort Walton Beach',
 'Niceville',
 'Okeechobee',
 'Orlando',
 'Ocoee',
 'Kissimmee',
 'Saint Cloud',
 'Delray Beach',
 'West Palm Beach',
 'Wellington',
 'Boca Raton',
 'Loxahatchee',
 'Belle Glade',
 'Palm Beach Gardens',
 'Jupiter',
 'Boynton Beach',
 'Atlantis',
 'Zephyrhills',
 'New Port Richey',
 'Trinity',
 'Dade City',
 'Hudson',
 'Safety Harbor',
 'St Petersburg',
 'Largo',
 'Kenneth City',
 'South Pasadena',
 'Clearwater',
 'Tarpon Springs',
 'Bay Pines',
 'Dunedin',
 'Lake Wales',
 'Winter Haven',
 'Davenport',
 'Bartow',
 'Lakeland',
 'Palatka',
 'St Augustine',
 'Fort Pierce',
 'Port St Lucie',
 'Gulf Breeze',
 'Milton',
 'Jay',
 'Sarasota',
 'Venice',
 'Sanford',
 'Live Oak',
 'Perry',
 'Orange City',
 'Daytona Beach',
 'Deland',
 'New Smyrna Beach',
 'Defuniak Springs',
 'Miramar Beach',
 'Chipley',
 'Baxley',
 'Alma',
 'Milledgeville',
 'Winder',
 'Cartersville',
 'Fitzgerald',
 'Macon',
 'Cochran',
 'Quitman',
 'Statesboro',
 'Waynesboro',
 'Saint Marys',
 'Metter',
 'Carrollton',
 'Villa Rica',
 'Fort Oglethorpe',
 'Savannah',
 'Johns Creek',
 'Canton',
 'Riverdale',
 'Homerville',
 'Austell',
 'Marietta',
 'Douglas',
 'Moultrie',
 'Adel',
 'Newnan',
 'Cordele',
 'Bainbridge',
 'Atlanta',
 'Lithonia',
 'Eastman',
 'Douglasville',
 'Blakely',
 'Springfield',
 'Elberton',
 'Swainsboro',
 'Claxton',
 'Blue Ridge',
 'Rome',
 'Cumming',
 'Lavonia',
 'Roswell',
 'Brunswick',
 'Calhoun',
 'Cairo',
 'Lawrenceville',
 'Snellville',
 'Demorest',
 'Bremen',
 'Stockbridge',
 'Warner Robins',
 'Ocilla',
 'Commerce',
 'Hazlehurst',
 'Dublin',
 'Hinesville',
 'Valdosta',
 'Thomson',
 'Montezuma',
 'Warm Springs',
 'Colquitt',
 'Camilla',
 'Forsyth',
 'Chatsworth',
 'Columbus',
 'Covington',
 'Hiram',
 'Byron',
 'Cedartown',
 'Hawkinsville',
 'Eatonton',
 'Cuthbert',
 'Conyers',
 'Donalsonville',
 'Griffin',
 'Toccoa',
 'Americus',
 'Thomasville',
 'Tifton',
 'Vidalia',
 'Hiawassee',
 'La Grange',
 'Blairsville',
 'Thomaston',
 'Monroe',
 'Waycross',
 'Sandersville',
 'Jesup',
 'Dalton',
 'Sylvester',
 'Hilo',
 'Kealakekua',
 'Kamuela',
 'Kahuku',
 'Honolulu',
 'Aiea',
 'Kailua',
 'Wahiawa',
 'Minneapolis',
 'St Louis Park',
 'Edina',
 'Robbinsdale',
 'Park Rapids',
 'Cambridge',
 'Grand Rapids',
 'Bigfork',
 'Deer River',
 'Mora',
 'Willmar',
 'Hallock',
 'International Falls',
 'Madison',
 'Dawson',
 'Two Harbors',
 'Baudette',
 'Le Sueur',
 'Hendricks',
 'Tyler',
 'Marshall',
 'Hutchinson',
 'Glencoe',
 'Mahnomen',
 'Fairmont',
 'Litchfield',
 'Onamia',
 'Princeton',
 'Little Falls',
 'Slayton',
 'Saint Peter',
 'Worthington',
 'Ada',
 'Rochester',
 'Fergus Falls',
 'Perham',
 'Thief River Falls',
 'Sandstone',
 'Pipestone',
 'Fosston',
 'Crookston',
 'Glenwood',
 'Maplewood',
 'Saint Paul',
 'Redwood Falls',
 'Olivia',
 'Northfield',
 'Faribault',
 'Roseau',
 'Virginia',
 'Duluth',
 'Hibbing',
 'Ely',
 'Cook',
 'Shakopee',
 'New Prague',
 'Arlington',
 'Sauk Centre',
 'Melrose',
 'Paynesville',
 'Owatonna',
 'Morris',
 'Staples',
 'Long Prairie',
 'Wheaton',
 'Wabasha',
 'Wadena',
 'Waseca',
 'Woodbury',
 'Stillwater',
 'Saint James',
 'Madelia',
 'Breckenridge',
 'Winona',
 'Buffalo',
 'Granite Falls',
 'Canby',
 'Natchez',
 'Corinth',
 'Kosciusko',
 'Cleveland',
 'Houston',
 'Port Gibson',
 'West Point',
 'Clarksdale',
 'Collins',
 'Southaven',
 'Hattiesburg',
 'Lucedale',
 'Grenada',
 'Bay St Louis',
 'Biloxi',
 'Gulfport',
 'Lexington',
 'Pascagoula',
 'Bay Springs',
 'Prentiss',
 'Laurel',
 'Oxford',
 'Meridian',
 'Tupelo',
 'Greenwood',
 'Brookhaven',
 'Holly Springs',
 'Amory',
 'Choctaw',
 'Philadelphia',
 'Starkville',
 'Picayune',
 'Poplarville',
 'McComb',
 'Pontotoc',
 'Whitfield',
 'Forest',
 'Morton',
 'Rolling Fork',
 'Mendenhall',
 'Magee',
 'Wiggins',
 'Ruleville',
 'Indianola',
 'Ripley',
 'Iuka',
 'New Albany',
 'Union',
 'Tylertown',
 'Vicksburg',
 'Eupora',
 'Water Valley',
 'Kirksville',
 'Fairfax',
 'Mexico',
 'Cassville',
 'Monett',
 'Butler',
 'Saint Joseph',
 'Poplar Bluff',
 'Fulton',
 'Osage Beach',
 'Cape Girardeau',
 'Harrisonville',
 'Belton',
 'North Kansas City',
 'Liberty',
 'Cameron',
 'Jefferson City',
 'Salem',
 'Sullivan',
 'Hermann',
 'Trenton',
 'Bethany',
 'West Plains',
 'Kansas City',
 'Lees Summit',
 'Independence',
 'Blue Springs',
 'Joplin',
 'Carthage',
 'Fenton',
 'Festus',
 'Warrensburg',
 'Lebanon',
 'Brookfield',
 'Chillicothe',
 'Hannibal',
 'Sikeston',
 'Neosho',
 'Maryville',
 'Hayti',
 'Perryville',
 'Sedalia',
 'Rolla',
 'Louisiana',
 'Bolivar',
 'Unionville',
 'Moberly',
 'Richmond',
 'St Charles',
 'Lake St Louis',
 'Saint Peters',
 'O Fallon',
 'Sainte Genevieve',
 'Saint Louis',
 'Bridgeton',
 'Chesterfield',
 'Creve Coeur',
 'Memphis',
 'Dexter',
 'Milan',
 'Branson',
 'Nevada',
 'Potosi',
 'Dillon',
 'Hardin',
 'Crow Agency',
 'Ekalaka',
 'Great Falls',
 'Fort Benton',
 'Miles City',
 'Scobey',
 'Glendive',
 'Anaconda',
 'Lewistown',
 'Whitefish',
 'Kalispell',
 'Bozeman',
 'Jordan',
 'Browning',
 'Cut Bank',
 'Havre',
 'Ronan',
 'Polson',
 'Fort Harrison',
 'Libby',
 'Circle',
 'Sheridan',
 'White Sulphur Springs',
 'Missoula',
 'Roundup',
 'Livingston',
 'Conrad',
 'Terry',
 'Sidney',
 'Wolf Point',
 'Culbertson',
 'Poplar',
 'Plains',
 'Plentywood',
 'Butte',
 'Big Timber',
 'Choteau',
 'Shelby',
 'Glasgow',
 'Harlowton',
 'Billings',
 'Hastings',
 'Neligh',
 'Albion',
 'Alliance',
 'Lynch',
 'Ainsworth',
 'Kearney',
 'David City',
 'Imperial',
 'Valentine',
 'Schuyler',
 'Callaway',
 'Broken Bow',
 'Chadron',
 'Cozad',
 'Gothenburg',
 'Omaha',
 'Benkelman',
 'Franklin',
 'Beatrice',
 'Oshkosh',
 'Grand Island',
 "O' Neill",
 'Atkinson',
 'Fairbury',
 'Tecumseh',
 'Minden',
 'Ogallala',
 'Kimball',
 'Creighton',
 'Lincoln',
 'North Platte',
 'Norfolk',
 'Central City',
 'Superior',
 'Syracuse',
 'Nebraska City',
 'Pawnee City',
 'Grant',
 'Holdrege',
 'Plainview',
 'Osmond',
 'McCook',
 'Falls City',
 'Bassett',
 'Friend',
 'Crete',
 'Papillion',
 'Wahoo',
 'Scottsbluff',
 ...]

In [40]:
df_definitive_set=set(df_definitive_hc_hospitalbeds["hq_city"].unique())

In [41]:
df_2016_set=set(df_2016["PlaceName"].unique())

In [43]:
#number of common cities between df_2016 match and df_definitive_hc_hospitalbeds

len(list(df_definitive_set.intersection(df_2016_set)))

430

In [44]:
#the common cities between df_2016 match and df_definitive_hc_hospitalbeds

list(df_definitive_set.intersection(df_2016_set))

['Fort Wayne',
 'Glendale',
 'Muncie',
 'Long Beach',
 'Newport News',
 'Gastonia',
 'Providence',
 'Sparks',
 'Oxnard',
 'Vancouver',
 'Largo',
 'Decatur',
 'Temecula',
 'Upland',
 'Hollywood',
 'Richmond',
 'Columbia',
 'Santa Monica',
 'Baytown',
 'Athens',
 'Denver',
 'Jackson',
 'Oceanside',
 'Columbus',
 'Roanoke',
 'Clovis',
 'San Mateo',
 'Anchorage',
 'Birmingham',
 'New Bedford',
 'Mobile',
 'San Diego',
 'West Covina',
 'Killeen',
 'Everett',
 'Louisville',
 'Yuma',
 'Norman',
 'Nashville',
 'Longmont',
 'Thousand Oaks',
 'Pleasanton',
 'Federal Way',
 'Midland',
 'Bolingbrook',
 'Renton',
 'Macon',
 'Greeley',
 'Akron',
 'Montgomery',
 'Rio Rancho',
 'Plymouth',
 'Manchester',
 'Allen',
 'North Las Vegas',
 'Gresham',
 'San Leandro',
 'Longview',
 'Springdale',
 'Layton',
 'Perris',
 'Meridian',
 'Johns Creek',
 'Westland',
 'Chicago',
 'Berkeley',
 'Quincy',
 'Clifton',
 'Union City',
 'Green Bay',
 'Bellevue',
 'Miramar',
 'Olathe',
 'Napa',
 'Wilmington',
 'Fort Collins',
 'Parma',
 'Chico',
 'Wichita',
 'College Station',
 'Medford',
 'Sacramento',
 'San Angelo',
 'Stockton',
 'Lansing',
 'Santa Barbara',
 'Odessa',
 'Fremont',
 'Cleveland',
 'Bethlehem',
 'Bridgeport',
 'Carmel',
 'Santa Fe',
 'Passaic',
 'Youngstown',
 'Minneapolis',
 'Portsmouth',
 'Murfreesboro',
 'Arlington Heights',
 'Abilene',
 'San Antonio',
 'Orlando',
 'Spokane',
 'New Orleans',
 'Clarksville',
 'Warner Robins',
 'Salem',
 'Gary',
 'Waterbury',
 'Stamford',
 'Broken Arrow',
 'Cape Coral',
 'Peoria',
 'Asheville',
 'Gilbert',
 'Madison',
 'Tracy',
 'Oklahoma City',
 'Cheyenne',
 'Buffalo',
 'Mountain View',
 'Santa Ana',
 'Provo',
 'Jonesboro',
 'Knoxville',
 'Hemet',
 'Virginia Beach',
 'Norfolk',
 'Henderson',
 'North Charleston',
 'Washington',
 'Tallahassee',
 'Bellflower',
 'Kansas City',
 'Antioch',
 'Huntsville',
 'Turlock',
 'Arlington',
 'Appleton',
 'Fontana',
 'Overland Park',
 'Fresno',
 'Rock Hill',
 'Jacksonville',
 'Redlands',
 'Rochester',
 'Fishers',
 'Livermore',
 'Newport Beach',
 'Thornton',
 'Avondale',
 'Miami',
 'Sioux City',
 'Vallejo',
 'Kent',
 'Murrieta',
 'Tampa',
 'Iowa City',
 'Apple Valley',
 'Loveland',
 'Laredo',
 'San Ramon',
 'Corona',
 'Boston',
 'Des Moines',
 'Mount Pleasant',
 'Toledo',
 'Tyler',
 'Lewisville',
 'Pasadena',
 'New Rochelle',
 'Farmington Hills',
 'Cranston',
 'Ann Arbor',
 'Albany',
 'Flint',
 'Orange',
 'Brownsville',
 'Corpus Christi',
 'Fort Worth',
 'Philadelphia',
 'Waukegan',
 'Garden Grove',
 'Hawthorne',
 'Sugar Land',
 'Joliet',
 'Newark',
 'Folsom',
 'Norwalk',
 'Las Vegas',
 'Sunrise',
 'Hayward',
 'Rapid City',
 'Fairfield',
 'Austin',
 'Redding',
 'Wichita Falls',
 'Boise City',
 'Costa Mesa',
 'Mission',
 'Charleston',
 'Bakersfield',
 'Menifee',
 'Indianapolis',
 'Palm Coast',
 'Canton',
 'Dayton',
 'Lake Forest',
 'Plantation',
 'Alhambra',
 'Scottsdale',
 'Lakewood',
 'Aurora',
 'Whittier',
 'Miami Beach',
 'Melbourne',
 'Racine',
 'Carlsbad',
 'South Bend',
 'McAllen',
 'Seattle',
 'Milwaukee',
 'Paterson',
 'Daly City',
 'Boynton Beach',
 'Fullerton',
 'Lubbock',
 'Erie',
 'New York',
 'Inglewood',
 'Hartford',
 'Davenport',
 'Camden',
 'Boca Raton',
 'Edmond',
 'Modesto',
 'Lincoln',
 'Chesapeake',
 'Sioux Falls',
 'Alameda',
 'Charlotte',
 'Jersey City',
 'Billings',
 'Irvine',
 'San Francisco',
 'Fayetteville',
 'Tempe',
 'Downey',
 'Mesquite',
 'Edinburg',
 'New Haven',
 'Fort Lauderdale',
 'Beaumont',
 'Ontario',
 'San Jose',
 'Boulder',
 'Yakima',
 'Colorado Springs',
 'Evansville',
 'Houston',
 'Huntington Beach',
 'Phoenix',
 'Fort Smith',
 'Springfield',
 'Lafayette',
 'Suffolk',
 'Clearwater',
 'Ogden',
 'Southfield',
 'Bloomington',
 'Little Rock',
 'Redwood City',
 'Honolulu',
 'Tacoma',
 'Bryan',
 'Elizabeth',
 'Raleigh',
 'Carrollton',
 'Rockford',
 'Westminster',
 'Yonkers',
 'Hillsboro',
 'Brockton',
 'Waterloo',
 'Augusta',
 'San Marcos',
 'Champaign',
 'Grand Rapids',
 'Indio',
 'Gainesville',
 'West Jordan',
 'Burbank',
 'Kenner',
 'Durham',
 'Bellingham',
 'Mesa',
 'Evanston',
 'Santa Maria',
 'Independence',
 'Sunnyvale',
 'Moreno Valley',
 'Waco',
 'Lake Charles',
 'Mission Viejo',
 'Palmdale',
 'Newton',
 'Somerville',
 'Manteca',
 'Vacaville',
 'Palm Bay',
 'Atlanta',
 'Kennewick',
 'Roseville',
 'Deltona',
 'Tustin',
 'Hialeah',
 'Dallas',
 'Concord',
 'Richardson',
 'Irving',
 'Kenosha',
 'Eugene',
 'Chino',
 'Tulsa',
 'Pearland',
 'Lowell',
 'League City',
 'Oakland',
 'Danbury',
 'Greenville',
 'Santa Rosa',
 'Missoula',
 'Tuscaloosa',
 'Reading',
 'High Point',
 'Visalia',
 'Naperville',
 'Riverside',
 'Chula Vista',
 'Spokane Valley',
 'Hammond',
 'Omaha',
 'Waukesha',
 'Surprise',
 'Los Angeles',
 'Hampton',
 'Elgin',
 'Burlington',
 'Pomona',
 'Plano',
 'Tucson',
 'Nashua',
 'Shreveport',
 'Pembroke Pines',
 'Garland',
 'Denton',
 'Merced',
 'Lancaster',
 'Baton Rouge',
 'Coral Springs',
 'Lakeland',
 'Duluth',
 'Gulfport',
 'Reno',
 'Albuquerque',
 'Amarillo',
 'Schenectady',
 'Lynwood',
 'Simi Valley',
 'Chattanooga',
 'Worcester',
 'Torrance',
 'Nampa',
 'Kalamazoo',
 'Sandy',
 'Frisco',
 'Fargo',
 'Cambridge',
 'Deerfield Beach',
 'Baltimore',
 'Memphis',
 'Chandler',
 'Orem',
 'Scranton',
 'Victorville',
 'Santa Clara',
 'Rancho Cucamonga',
 'Alexandria',
 'Escondido',
 'Detroit',
 'Cincinnati',
 'San Bernardino',
 'Topeka',
 'Trenton',
 'Allentown',
 'Pueblo',
 'Anaheim',
 'Livonia',
 'Fall River',
 'Cedar Rapids',
 'Round Rock',
 'West Palm Beach',
 'Portland',
 'Lawrence',
 'Troy',
 'Warren',
 'Dearborn',
 'Brooklyn Park',
 'Auburn',
 'Wyoming',
 'Lexington',
 'Roswell',
 'Warwick',
 'Savannah',
 'El Paso',
 'Salinas',
 'McKinney',
 'Syracuse',
 'Mount Vernon',
 'Greensboro',
 'Lawton',
 'Cary',
 'Salt Lake City',
 'Pittsburgh',
 'Baldwin Park',
 'New Britain',
 'Las Cruces',
 'Bend',
 'Davie',
 'Lynchburg']

In [45]:
#The column: Population2010 is vague. Assuming it means the population in the city in the dataset, the unavoidable 
#question becomes: can i use the same population now. Also it for sure would have changed due to COVID. But in this 
#notebook I am planning to build a time series model with the data I have. I have to get the up-to-date data from the 
#streaming service anyway. Also it's possible to figure out a way to find the population in each city now or maybe a 
#within range + or - some percentage change? 
#for now I ought to try time series analysis to model the number of potential patients in each city

df_2016.head()

,StateAbbr,PlaceName,PlaceFIPS,Population2010,ACCESS2_CrudePrev,ACCESS2_Crude95CI,ACCESS2_AdjPrev,ACCESS2_Adj95CI,ARTHRITIS_CrudePrev,ARTHRITIS_Crude95CI,...,SLEEP_Adj95CI,STROKE_CrudePrev,STROKE_Crude95CI,STROKE_AdjPrev,STROKE_Adj95CI,TEETHLOST_CrudePrev,TEETHLOST_Crude95CI,TEETHLOST_AdjPrev,TEETHLOST_Adj95CI,Geolocation
0,FL,Deltona,1217200,"85,182",24.3,"(23.7, 25.0)",23.7,"(23.0, 24.3)",26.0,"(25.8, 26.3)",...,"(36.8, 37.5)",3.2,"( 3.2, 3.3)",3.0,"( 3.0, 3.1)",14.8,"(13.8, 15.8)",14.8,"(13.8, 15.8)","(28.905060048, -81.2134269839)"
1,FL,Fort Lauderdale,1224000,"165,521",22.5,"(22.0, 23.0)",22.0,"(21.5, 22.6)",25.8,"(25.7, 26.1)",...,"(38.1, 38.6)",3.6,"( 3.5, 3.6)",3.2,"( 3.2, 3.3)",12.1,"(11.3, 12.8)",12.1,"(11.3, 12.8)","(26.1418205174, -80.1471225502)"
2,NC,Fayetteville,3722920,"200,564",21.0,"(20.6, 21.4)",19.2,"(18.8, 19.5)",24.4,"(24.3, 24.6)",...,"(39.7, 40.1)",3.1,"( 3.1, 3.2)",3.6,"( 3.5, 3.7)",18.3,"(17.5, 19.3)",18.4,"(17.4, 19.4)","(35.0851309527, -78.9791676456)"
3,NC,Gastonia,3725580,"71,741",25.3,"(24.7, 25.8)",24.6,"(24.1, 25.2)",30.0,"(29.7, 30.3)",...,"(38.4, 39.0)",4.0,"( 3.9, 4.1)",3.7,"( 3.7, 3.8)",22.4,"(21.0, 24.0)",22.2,"(20.9, 23.9)","(35.2472984431, -81.1836588468)"
4,CA,Lake Forest,639496,"77,264",11.4,"(10.9, 11.9)",11.0,"(10.6, 11.6)",17.5,"(17.2, 17.8)",...,"(29.9, 30.6)",2.0,"( 2.0, 2.1)",2.2,"( 2.1, 2.3)",8.2,"( 6.9, 9.8)",8.3,"( 7.1, 9.9)","(33.6634128948, -117.670683341)"

In [ ]:
#Let's understand the meaning of the fields that we are interested in as follows:

CANCER_AdjPrev	Model-based estimate for age-adjusted prevalence of cancer (excluding skin cancer) among adults aged >=18 years, 2014


CHD_AdjPrev	Model-based estimate for age-adjusted prevalence of coronary heart disease among adults aged >=18 years, 2014


KIDNEY_AdjPrev	Model-based estimate for age-adjusted prevalence of chronic kidney disease among adults aged >=18 years, 2014

StateAbbr	PlaceName	Population2010

Also not sure whether to include age adjusted percentage values as such or use the values in the 95% confidence 
interval range for these fields?! For now using the above mentioned values. 


Also note:
2014, 2013. Data were provided by the Centers for Disease Control and Prevention (CDC), Division of Population Health, 
Epidemiology and Surveillance Branch. The project was funded by the Robert Wood Johnson Foundation (RWJF) in 
conjunction with the CDC Foundation. 500 cities project census city-level data in GIS-friendly format can be 
joined with city spatial data (https://chronicdata.cdc.gov/500-Cities/500-Cities-City-Boundaries/n44h-hy2j) in a 
geographic information system (GIS) to produce maps of 27 measures at the city-level.

In [46]:
#Not sure what it means by 2013 and 2014 for the above report that's released in 2016. For now rolling with the data. 
#the data is demonstrated in percentage values

#Let's get the necessary fields and values



df_2016_necessary=df_2016[["StateAbbr","PlaceName","Population2010","CANCER_AdjPrev","CHD_AdjPrev","KIDNEY_AdjPrev"]]

In [47]:
df_2016_necessary.head()

,StateAbbr,PlaceName,Population2010,CANCER_AdjPrev,CHD_AdjPrev,KIDNEY_AdjPrev
0,FL,Deltona,"85,182",6.2,6.7,3.1
1,FL,Fort Lauderdale,"165,521",6.2,6.4,3.2
2,NC,Fayetteville,"200,564",5.7,6.6,2.7
3,NC,Gastonia,"71,741",6.0,7.1,2.7
4,CA,Lake Forest,"77,264",5.9,4.8,2.2

In [48]:
#The next step is to groupby the values according to the cities as there are multiple values for some cities

df_2016_necessary["PlaceName"].value_counts()

Springfield    3
Bloomington    3
Columbia       2
Pasadena       2
Peoria         2
              ..
Tallahassee    1
Garland        1
Bellflower     1
Renton         1
Kennewick      1
Name: PlaceName, Length: 474, dtype: int64

In [51]:
#let's check the nature of the multiple values. Why there are in the first place? So it is rather important to consider
#the place names according to their state

df_2016_necessary.loc[df_2016_necessary["PlaceName"]=="Springfield"]

,StateAbbr,PlaceName,Population2010,CANCER_AdjPrev,CHD_AdjPrev,KIDNEY_AdjPrev
206,IL,Springfield,"116,250",6.0,5.9,2.5
230,MO,Springfield,"159,498",6.4,6.8,2.4
282,MA,Springfield,"153,060",6.0,7.3,4.3

In [52]:

df_2016_necessary.loc[df_2016_necessary["PlaceName"]=="Bloomington"]

,StateAbbr,PlaceName,Population2010,CANCER_AdjPrev,CHD_AdjPrev,KIDNEY_AdjPrev
211,MN,Bloomington,"82,893",5.9,4.7,1.9
265,IN,Bloomington,"80,405",6.2,6.3,2.5
313,IL,Bloomington,"76,610",6.0,5.6,2.4

In [56]:
#how about we pick a state and check all the cities within the state to verify whether there are multiple values per city
#within the state

len(df_2016_necessary.loc[df_2016_necessary["StateAbbr"]=="CA", "PlaceName"].tolist())

121

In [60]:
#let's create a dictionary to verify the above.

dict(df_2016_necessary.loc[df_2016_necessary["StateAbbr"]=="CA", "PlaceName"].value_counts())

#clearly there is a single value per city wihtin CA state

{'Newport Beach': 1,
 'Alameda': 1,
 'Escondido': 1,
 'Fullerton': 1,
 'Carson': 1,
 'Upland': 1,
 'Menifee': 1,
 'Oakland': 1,
 'San Bernardino': 1,
 'Richmond': 1,
 'Santa Monica': 1,
 'Pasadena': 1,
 'Clovis': 1,
 'Redondo Beach': 1,
 'Westminster': 1,
 'Santa Rosa': 1,
 'Costa Mesa': 1,
 'San Ramon': 1,
 'San Buenaventura (Ventura)': 1,
 'San Diego': 1,
 'Orange': 1,
 'Santa Ana': 1,
 'Perris': 1,
 'Anaheim': 1,
 'Oxnard': 1,
 'San Mateo': 1,
 'Visalia': 1,
 'Tracy': 1,
 'Riverside': 1,
 'Daly City': 1,
 'San Leandro': 1,
 'Downey': 1,
 'Whittier': 1,
 'Lynwood': 1,
 'Roseville': 1,
 'Glendale': 1,
 'Tustin': 1,
 'Torrance': 1,
 'Citrus Heights': 1,
 'Concord': 1,
 'Long Beach': 1,
 'Lake Forest': 1,
 'Alhambra': 1,
 'Vallejo': 1,
 'Lakewood': 1,
 'Murrieta': 1,
 'Temecula': 1,
 'Santa Clarita': 1,
 'Redwood City': 1,
 'Milpitas': 1,
 'Simi Valley': 1,
 'Vista': 1,
 'Ontario': 1,
 'Chino': 1,
 'Carlsbad': 1,
 'Apple Valley': 1,
 'Victorville': 1,
 'Santa Clara': 1,
 'Rancho Cucamonga': 1,
 'Chula Vista': 1,
 'Berkeley': 1,
 'Pleasanton': 1,
 'Garden Grove': 1,
 'Stockton': 1,
 'Antioch': 1,
 'Inglewood': 1,
 'Merced': 1,
 'Thousand Oaks': 1,
 'Lancaster': 1,
 'South Gate': 1,
 'Mission Viejo': 1,
 'West Covina': 1,
 'Turlock': 1,
 'San Marcos': 1,
 'Fontana': 1,
 'Hesperia': 1,
 'Modesto': 1,
 'Fresno': 1,
 'Palmdale': 1,
 'Santa Barbara': 1,
 'Baldwin Park': 1,
 'Huntington Beach': 1,
 'Manteca': 1,
 'Vacaville': 1,
 'Bakersfield': 1,
 'Oceanside': 1,
 'Fremont': 1,
 'El Cajon': 1,
 'Livermore': 1,
 'Elk Grove': 1,
 'Moreno Valley': 1,
 'Redding': 1,
 'Sunnyvale': 1,
 'Napa': 1,
 'Hawthorne': 1,
 'Union City': 1,
 'Mountain View': 1,
 'Chino Hills': 1,
 'Irvine': 1,
 'Corona': 1,
 'Indio': 1,
 'San Francisco': 1,
 'Redlands': 1,
 'Rialto': 1,
 'Los Angeles': 1,
 'Compton': 1,
 'Burbank': 1,
 'Bellflower': 1,
 'Hemet': 1,
 'Pomona': 1,
 'Folsom': 1,
 'Buena Park': 1,
 'Norwalk': 1,
 'Chico': 1,
 'El Monte': 1,
 'Sacramento': 1,
 'Santa Maria': 1,
 'Salinas': 1,
 'Fairfield': 1,
 'San Jose': 1,
 'Hayward': 1}